[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/playbook-download"
  to = "/playbook-download.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
